# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: GitHub metrics as SVG image

on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: "master"}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: SpraxDev
          template: classic
          base: activity, repositories, metadata

          plugin_languages: yes
          plugin_lines: yes
